baseURL = "http://manuelsocias.github.io"
languageCode = "es"
defaultContentLanguage = "es"
title = "MS"
theme = "hallo-hugo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Manuel Socías"

[params]

    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:manuel.salvador.socias@gmail.com"

    [[params.links]]
        icon = "instagram"
        title = "Instagram"
        url = "https://www.instagram.com/manuelsocias/"

    [[params.links]]
        icon = "twitter"
        title = "Twitter"
        url = "https://twitter.com/manuelsocias"
      
